### ISSUE TITLE
Follow the instructions for how to create the Product Backlog add set up a Sprint Backlog and Task Board

### ISSUE THREAD

**Issue by bloombar** [nyu-software-engineering/nyu-classes-auth-bypass#10]
I see you have only a few issues in the Issues tracker, and you have placed "cards" on the task board.  These cards are not issues in the issue tracker, and should be avoided in this course.    You also have not set up your labels or milestones.

The Product backlog at this point should consist of a mix of user stories and spikes, plus any tasks you have created based on your user stories.  Your Task Board for Sprint 0 should show which of these user stories or spikes you are currently working on, and any tasks you have created from those user stories.  

Follow [the instructions for making issues](https://knowledge.kitchen/Software_engineering_project_kickoff#Create_the_initial_product_backlog) and [placing them on the task board](https://knowledge.kitchen/Software_engineering_project_kickoff#Plan_sprint_0).

**Comment by jjc750** [comment]
Labels, milestones, and product backlog created
